### ISSUE TITLE
Ensure robotcode can compile after upgrading to the new 2022 wpilib

### ISSUE THREAD

**Issue by flynneva** [Tritron-Robotics/robotcode2022#1]
See [the build CI action](https://github.com/Tritron-Robotics/robotcode2022/runs/4876435631?check_suite_focus=true) for details.

**Comment by An3Dev** [comment]
I found a potential solution here: https://www.chiefdelphi.com/t/new-command-framework-missing-from-wpilib-install/370351/4

**Comment by An3Dev** [comment]
I fixed the errors by installing the REVLib library, New Command System library, and the Kauailabs library. I installed them from visual studio.

**Comment by flynneva** [comment]
@An3Dev great stuff! Looks like CI is passing now as well! 👍
