### ISSUE TITLE
make first 0.1.0 release as a baseline

### ISSUE THREAD

**Issue by flynneva** [Tritron-Robotics/robotcode2022#17]
In software development releases are everything and help you keep track of existing features, new features and even bugs (e.g. if a bug has existed in previous releases too).

The best way to do releases is with [the basic `git tag` approach](https://git-scm.com/book/en/v2/Git-Basics-Tagging). Tagging code allows you to plant a flag in the ground and say "this is the features that exist at this point in time". Once you tag the code, you release the tag and let everyone (e.g. other teams, customers, etc.) use that release while you (the software team) continue working in the background on the next release.

Basic tagging workflow goes like this:

1. Confirm the code you have at the current `git commit` works as expected at that moment in time
    1. unit tests / integration tests can automate this step (and give you logs to prove it 😄)
    1. We already have sort of done this manually in #2
1. Record what [current features exist in a `CHANGELOG` file](https://keepachangelog.com/en/1.0.0/) and commit it
    1. We will update this `CHANGELOG` just before each new release going forward to keep track of whats changed / whats been added
    2. Some people also call this file `release-notes` if you want, essentially its the same thing
1. Once the `CHANGELOG` has been updated and committed, create the tag with `git tag 0.0.1`
    1. [Semantic Versioning](https://semver.org/) is generally the standard so it goes *major.minor.patch*
    2. Major: usually incrementing this means breaking changes were made to the code or lots of new features
    3. Minor: usually incrementing this means minor updates / fixes / enhancements were made since the last release
    4. Patch: usually incrementing this means just patches / fixes to existing code were made
    5. Example: 0.1.0 would be a good first release number, 0.1.1 would be a good patch number, 1.0.0 would be a good first stable / feature complete release
1. After tag is created locally, push it to the remote repo with `git push --tags`
1. After that, the tag should [show up on the repo under releases / tags](https://github.com/Tritron-Robotics/robotcode2022/tags)
1. From there, you can use github in the browser to upgrade a `tag` to an official `release`

**Comment by flynneva** [comment]
As a side note, you can also automate the release pipeline using Github Actions.

although this can get out of hand really quickly and needs to be done carefully as it is very hard to automate when a release is a major, minor or patch release.

**Comment by flynneva** [comment]
Having this first `0.1.0` should also let us track what features / functions were added during development this year, which will be cool to look back at and see what you guys did!

**Comment by An3Dev** [comment]
Finally added tags!
