### ISSUE TITLE
How to contribute to `main` and push changes

### ISSUE THREAD

**Issue by flynneva** [Tritron-Robotics/robotcode2022#7]
### How to Contribute

Typical `git` development involves the following steps:

1. Clone the repository you want to change:
    - `git clone` repository
2. Checkout new branch to make your changes on:
    - `git checkout -b  my-new-branch`
    - usually the name of the branch should describe its purpose (i.e. `add-readme` would be a great branch name)
3. Commit changes locally to your new branch:
    - `git add .`
    - `git commit -m "my really awesome feature"
4. Push local changes to remote repositry (github):
    - `git push`
5. Make pull request on github:
    - in the browser, go to `github.com` and go to the `Pull Request` tab

### Why is this important?

As the software team gets larger, more and more people will contribute to the code. If everyone is pushing to the same `main` branch at the same time...things can get ugly 🚫  and end up causing problems for all the developers on the project.

Doing development this way, the `main` branch should *always be functional code* and also the main starting point for everyone to branch off of.

### How to fix this

Let's add the above steps to the new `How to contribute` section in our `README.md`:

- [x] add above steps to `How to contribute` section within `README`

**Comment by flynneva** [comment]
@An3Dev @BallsAngus @jsakeag @Jtuazon25 I've noticed you guys are just pushing commits directly to `main` so I've added protections to that branch to stop that 😅 

If you want to upload changes to this repo follow the steps above and make a `Pull Request`, that way we can all review the changes before they happen 👍🏼 💯

**Comment by flynneva** [comment]
Following these steps should also enable us to run `CI / CD` tests automatically on the `Pull Request`...which should test the new code you guys write automatically!

**Comment by An3Dev** [comment]
Added the `How to contribute` section.
